language: scala
scala:
   - 2.11.8
   - 2.12.1
script: "sbt clean coverage test"
after_success: "sbt coverageReport && bash <(curl -s https://codecov.io/bash)"

cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2/cache

sudo: false